### ISSUE TITLE
Forks of invoicer will not build on CircleCI

### ISSUE THREAD

**Issue by rigoford** [Securing-DevOps/invoicer#8]
'Out of the box' a fork of this repo will not build on CircleCI since the DOCKER_REPO environment variable is blank.

If you look at the output of the CircleCI build, under the **MACHINE** section, you get a subsection entitled **Exporting env vars from circle.yml** just before a subsection entitled **Exporting env vars from project settings**.

The following line in the circle.yml will therefore not evaluate as expected:

`DOCKER_REPO: "$(if [ $CIRCLE_PROJECT_USERNAME == 'Securing-DevOps' ]; then echo securingdevops; else echo $DOCKER_USER; fi)"`

The **DOCKER_USER** environment variable hasn't been set yet...

**Comment by jvehent** [comment]
Commit https://github.com/Securing-DevOps/invoicer/commit/f366fb0558e6c83e3faa712409ba72dea194ea19 should fix the issue. Could you rebase and try again on your fork?
